# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-30 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
